DEFAULT_COURSE_SLUG = "python-data-analyst"
LLM_RAG_COURSE_SLUG = "llm-rag"
EXCEL_DATA_ANALYST_COURSE_SLUG = "excel-data-analyst"
POWER_BI_DATA_ANALYST_COURSE_SLUG = "power-bi-data-analyst"
SQL_DATA_ANALYST_COURSE_SLUG = "sql-data-analyst"
STATISTICS_DATA_SCIENCE_PYTHON_COURSE_SLUG = "statistics-data-science-python"
MACHINE_LEARNING_PYTHON_COURSE_SLUG = "machine-learning-python"

COURSE_NOT_FOUND = "Parcours introuvable ou non publié."
MODULE_NOT_FOUND = "Module introuvable ou non publié."
MODULE_SCOPE_ERROR = "Module introuvable dans ce parcours."
LESSON_NOT_FOUND = "Leçon introuvable ou non publiée."
EXERCISE_NOT_FOUND = "Exercice introuvable ou non publié."
PROJECT_NOT_FOUND = "Projet introuvable ou non publié."
THEORY_RESOURCE_NOT_FOUND = "Support théorique introuvable ou non publié."
