from pathlib import Path

modules = [
(0,"Raisonnement statistique",[("qcm","Quelle distinction est indispensable avant une analyse ?",["Population et échantillon","Moyenne et somme","CSV et JSON","Python et SQL"],"A","La population est la cible, l’échantillon la partie observée."),("true_false","Une corrélation observée suffit à prouver une causalité.",["Vrai","Faux","Toujours en régression","Seulement avec pandas"],"B","Une association ne prouve pas un lien causal."),("comprehension","Quel type de variable est un niveau de satisfaction ordonné ?",["Ordinale","Nominale","Continue","Identifiant"],"A","Les catégories sont ordonnées sans distance nécessairement constante."),("mini_challenge","Quelle première étape rend une question métier testable ?",["Définir population, variable cible et comparaison","Choisir un modèle complexe","Supprimer les valeurs extrêmes","Calculer une p-value"],"A","Le cadrage précède les calculs.")]),
(1,"Statistiques descriptives",[("qcm","Quelle mesure résiste mieux aux valeurs extrêmes ?",["Médiane","Moyenne","Variance","Étendue"],"A","La médiane dépend de l’ordre, pas de l’amplitude des extrêmes."),("true_false","Un écart-type nul signifie que toutes les valeurs sont identiques.",["Vrai","Faux","Seulement pour un échantillon","Impossible"],"A","Une dispersion nulle implique une valeur constante."),("comprehension","Que mesure l’intervalle interquartile ?",["La dispersion des 50 % centraux","La moyenne des valeurs","Le nombre de lignes","La causalité"],"A","IQR = Q3 - Q1."),("mini_challenge","Pour une distribution très asymétrique, quel résumé est le plus robuste ?",["Médiane et IQR","Moyenne seule","Maximum seul","Somme et nombre"],"A","Médiane et IQR résistent mieux aux extrêmes.")]),
(2,"Distributions",[("qcm","Quel graphique montre médiane, quartiles et valeurs atypiques ?",["Boxplot","Camembert","Carte","Table brute"],"A","Le boxplot synthétise position et dispersion."),("true_false","Une distribution symétrique est nécessairement normale.",["Vrai","Faux","Toujours avec n>30","Seulement après standardisation"],"B","La symétrie ne suffit pas à caractériser la normalité."),("comprehension","Que peut révéler un histogramme multimodal ?",["Plusieurs sous-populations","Une causalité certaine","Une erreur Python","Une moyenne nulle"],"A","Plusieurs pics peuvent signaler des groupes distincts."),("mini_challenge","Pourquoi appliquer parfois log1p à une variable monétaire ?",["Réduire l’asymétrie tout en gérant zéro","Créer des données","Supprimer les unités","Garantir la causalité"],"A","La transformation compresse les grandes valeurs.")]),
(3,"Probabilités",[("qcm","Quelle notation décrit P(A sachant B) ?",["P(A|B)","P(A+B)","P(A-B)","P(A*B)"],"A","La barre verticale représente la condition."),("true_false","Deux événements indépendants peuvent être mutuellement exclusifs avec probabilités positives.",["Vrai","Faux","Toujours","Seulement si égaux"],"B","S’ils sont exclusifs et positifs, observer l’un change la probabilité de l’autre."),("comprehension","Quelle loi modélise un nombre de succès sur n essais indépendants ?",["Binomiale","Normale","Uniforme","Exponentielle"],"A","La loi binomiale compte les succès de Bernoulli."),("mini_challenge","Quelle règle permet d’inverser une probabilité conditionnelle ?",["Théorème de Bayes","Loi des grands nombres","ANOVA","Bootstrap"],"A","Bayes relie P(A|B) et P(B|A).")]),
(4,"Échantillonnage et bootstrap",[("qcm","Que quantifie l’erreur standard ?",["La variabilité d’un estimateur","La dispersion brute seulement","Le nombre de colonnes","Une erreur de saisie"],"A","Elle mesure la variabilité d’échantillonnage."),("true_false","Le bootstrap rééchantillonne avec remise.",["Vrai","Faux","Jamais","Seulement deux fois"],"A","Les réplications bootstrap tirent avec remise."),("comprehension","Un intervalle de confiance à 95 % signifie-t-il 95 % de probabilité pour ce paramètre fixe ?",["Non, en interprétation fréquentiste","Oui toujours","Seulement avec pandas","Seulement si n=100"],"A","Le niveau concerne la procédure répétée."),("mini_challenge","Quel biais menace un sondage diffusé seulement aux clients actifs ?",["Biais de sélection","Biais de compilation","Biais de syntaxe","Biais de tri"],"A","Les non-actifs ne peuvent pas être représentés.")]),
(5,"Tests d’hypothèses",[("qcm","Que représente la p-value ?",["La probabilité d’un résultat au moins aussi extrême sous H0","La probabilité que H0 soit vraie","La taille d’effet","La puissance"],"A","La p-value est conditionnelle à H0 et au modèle."),("true_false","Réduire alpha augmente, toutes choses égales, le risque d’erreur de type II.",["Vrai","Faux","Jamais","Seulement en ANOVA"],"A","Une règle plus stricte réduit la puissance à taille fixe."),("comprehension","Que mesure la puissance d’un test ?",["La probabilité de détecter un effet réel donné","La taille de l’échantillon","La p-value minimale","La variance totale"],"A","Puissance = 1 - bêta."),("mini_challenge","Quelle pratique évite de choisir le test après avoir vu le résultat ?",["Préspécifier hypothèses et méthode","Essayer jusqu’à p<0,05","Supprimer les groupes","Changer alpha après coup"],"A","La préspécification limite le p-hacking.")]),
(6,"Comparer des groupes",[("qcm","Quelle variante du t-test gère mieux des variances inégales ?",["Welch","Student à variances égales","Chi-deux","Pearson"],"A","Welch n’impose pas l’égalité des variances."),("true_false","Mann-Whitney teste toujours uniquement une différence de médiane.",["Vrai","Faux","Seulement si n>30","Toujours avec scipy"],"B","Il porte sur les distributions/rangs ; la lecture médiane exige des conditions."),("comprehension","Après une ANOVA significative, que faut-il ajouter ?",["Des comparaisons post-hoc contrôlées","Un second histogramme uniquement","Une régression logistique","Aucune analyse"],"A","Le test global ne localise pas les différences."),("mini_challenge","Quelle taille d’effet convient à un tableau de contingence ?",["V de Cramér","Cohen d","R carré ajusté","MAE"],"A","Le V de Cramér quantifie l’association catégorielle.")]),
(7,"Corrélation et régression",[("qcm","Pearson mesure principalement quelle relation ?",["Linéaire","Nominale","Causale","Saisonnière"],"A","Pearson résume une association linéaire."),("true_false","Spearman travaille sur les rangs.",["Vrai","Faux","Seulement les moyennes","Seulement les résidus"],"A","Il mesure une association monotone via les rangs."),("comprehension","Dans une régression multiple, un coefficient s’interprète comment ?",["Toutes choses égales par ailleurs","Comme une causalité certaine","Sans tenir compte des autres variables","Comme une corrélation de rang"],"A","Il est conditionnel aux variables incluses."),("mini_challenge","Quel diagnostic révèle une variance des résidus croissante ?",["Graphique résidus vs valeurs ajustées","Histogramme des identifiants","Table des noms","Compteur de colonnes"],"A","Une forme en entonnoir suggère l’hétéroscédasticité.")]),
(8,"Segmentation client",[("qcm","Pourquoi standardiser avant KMeans ?",["Éviter qu’une grande échelle domine les distances","Garantir K=3","Supprimer les clusters","Créer des labels"],"A","KMeans dépend des distances euclidiennes."),("true_false","Un identifiant client numérique doit être utilisé dans la distance.",["Vrai","Faux","Toujours","Seulement s’il est unique"],"B","Un identifiant n’a pas de sens métrique."),("comprehension","Que combine-t-on pour choisir K ?",["Inertie, silhouette, stabilité et utilité métier","Seulement le coude","Seulement le nombre de clients","Seulement la moyenne"],"A","Aucun indicateur unique ne suffit."),("mini_challenge","Quelle étape rend un cluster actionnable ?",["Profiler ses distributions et comportements","Le renommer au hasard","Masquer sa taille","Supprimer les médianes"],"A","Le profilage traduit le groupe en caractéristiques métier.")]),
(9,"Prévision des ventes",[("qcm","Quel découpage respecte la causalité temporelle ?",["Entraîner sur le passé, tester sur le futur","Mélanger toutes les dates","Tester sur le passé","Trier après prédiction"],"A","La validation doit simuler l’usage réel."),("true_false","La MAPE est stable lorsque les ventes réelles sont proches de zéro.",["Vrai","Faux","Toujours","Seulement mensuellement"],"B","Le dénominateur proche de zéro la rend instable."),("comprehension","Quelle baseline exploite une saisonnalité hebdomadaire ?",["Valeur observée sept jours plus tôt","Moyenne future","Échantillon aléatoire","Maximum global"],"A","La baseline saisonnière répète le cycle connu."),("mini_challenge","Pourquoi utiliser une validation walk-forward ?",["Simuler plusieurs décisions successives dans le temps","Créer plus de variables","Supprimer la saisonnalité","Garantir une erreur nulle"],"A","Elle évalue la stabilité selon plusieurs origines de prévision.")]),
(10,"Évaluation des modèles",[("qcm","Quel jeu doit rester verrouillé jusqu’à l’évaluation finale ?",["Test","Train","Documentation","Dictionnaire"],"A","Le test final doit rester indépendant."),("true_false","La standardisation doit être apprise séparément dans chaque fold.",["Vrai","Faux","Jamais","Seulement pour les arbres"],"A","Sinon les folds de validation influencent la transformation."),("comprehension","Que suggère un score train excellent et validation faible ?",["Surapprentissage","Sous-échantillonnage certain","Causalité","Absence de modèle"],"A","Le modèle généralise mal."),("mini_challenge","Pourquoi l’importance de permutation peut-elle être trompeuse avec variables corrélées ?",["Une variable peut être remplacée par sa corrélée","Elle devient causale","La cible disparaît","Les folds doublent"],"A","L’information redondante réduit la baisse de score individuelle.")]),
(11,"Communication",[("qcm","Quel ordre sert une restitution métier ?",["Question, méthode, résultat, limites, recommandation","Code, code, code","Conclusion avant données sans preuve","Graphiques sans titres"],"A","La narration relie besoin, preuve et action."),("true_false","Un notebook reproductible doit pouvoir être exécuté depuis un environnement propre.",["Vrai","Faux","Seulement en local","Jamais"],"A","L’état caché doit être éliminé."),("comprehension","Que doit distinguer une restitution honnête ?",["Faits, interprétations et décisions","Couleurs et polices","Python et clavier","CSV et écran"],"A","Ces niveaux n’ont pas le même statut de preuve."),("mini_challenge","Quel garde-fou accompagne une recommandation sensible ?",["Revue humaine et suivi par sous-groupe","Automatisation sans contrôle","Suppression des limites","Collecte maximale"],"A","La supervision et l’équité réduisent le risque.")]),
]

final_questions=[
("Quelle mesure robuste résume le centre d’une distribution asymétrique ?",["Médiane","Moyenne","Variance","Étendue"]),
("Quelle méthode estime l’incertitude par rééchantillonnage avec remise ?",["Bootstrap","ANOVA","KMeans","PCA"]),
("Que complète idéalement une p-value ?",["Une taille d’effet et un intervalle de confiance","Un logo","Une clé primaire","Un tri alphabétique"]),
("Quel test compare plusieurs moyennes ?",["ANOVA","Pearson","KMeans","MAE"]),
("Quelle corrélation convient à une relation monotone sur rangs ?",["Spearman","Pearson uniquement","Chi-deux","Cohen d"]),
("Pourquoi standardiser avant KMeans ?",["Mettre les variables sur des échelles comparables","Choisir automatiquement K","Créer la cible","Supprimer les clients"]),
("Quel découpage convient aux séries temporelles ?",["Passé pour train, futur pour test","Aléatoire sans date","Futur pour train","Aucun test"]),
("Quelle métrique pénalise davantage les grosses erreurs ?",["RMSE","MAE","Médiane","Silhouette"]),
("Quel signe classique indique le surapprentissage ?",["Grand écart train-validation","Deux colonnes","Une moyenne nulle","Un index datetime"]),
("Une importance de variable prouve-t-elle la causalité ?",["Non","Oui toujours","Seulement avec forêt","Seulement avec régression"]),
("Que faut-il fixer pour rendre une analyse reproductible ?",["Dépendances, graines, données et ordre d’exécution","Couleur du thème seulement","Taille d’écran","Nom du dossier seul"]),
("Quel principe guide une recommandation responsable ?",["Proportionner la décision aux preuves et documenter les risques","Masquer l’incertitude","Collecter toutes les données","Automatiser sans contrôle"]),
]

def esc(v): return v.replace("'","''")
def opts(values): return "jsonb_build_array("+",".join("'%s'"%esc(f"{chr(65+i)}) {v}") for i,v in enumerate(values))+")"

parts=["""-- KORYXA FORMATION — STATISTIQUES & DATA SCIENCE AVEC PYTHON — CHANTIER 4
-- Quiz par module, test final et projet final. Contenus non publiés.

ALTER TABLE public.quiz_questions
ADD COLUMN IF NOT EXISTS question_type TEXT NOT NULL DEFAULT 'qcm'
CHECK (question_type IN ('qcm','true_false','comprehension','mini_challenge')),
ADD COLUMN IF NOT EXISTS is_final_test BOOLEAN NOT NULL DEFAULT FALSE;
"""]
for module_order,skill,questions in modules:
    values=[]
    for i,(qt,q,answers,answer,explanation) in enumerate(questions,1):
        difficulty="avance" if qt=="mini_challenge" else "intermediaire" if qt=="comprehension" else "debutant"
        values.append(f"({i},'{qt}','{esc(q)}',{opts(answers)},'{answer}','{difficulty}','{esc(skill)}','{esc(explanation)}')")
    parts.append(f"""WITH target_module AS (SELECT m.id FROM public.modules m JOIN public.courses c ON c.id=m.course_id WHERE c.slug='statistics-data-science-python' AND m.order_index={module_order}), seed(order_index,question_type,question,options,answer,difficulty,skill,explanation) AS (VALUES {','.join(values)})
INSERT INTO public.quiz_questions(module_id,order_index,question_type,question,options,answer,difficulty,skill,explanation,is_active,is_final_test)
SELECT target_module.id,s.order_index,s.question_type,s.question,s.options,s.answer,s.difficulty,s.skill,s.explanation,FALSE,FALSE FROM target_module CROSS JOIN seed s
ON CONFLICT(module_id,order_index) DO UPDATE SET question_type=EXCLUDED.question_type,question=EXCLUDED.question,options=EXCLUDED.options,answer=EXCLUDED.answer,difficulty=EXCLUDED.difficulty,skill=EXCLUDED.skill,explanation=EXCLUDED.explanation,is_active=FALSE,is_final_test=FALSE;
""")
values=[]
for i,(q,answers) in enumerate(final_questions,101): values.append(f"({i},'qcm','{esc(q)}',{opts(answers)},'A','intermediaire','synthèse','La bonne réponse est {esc(answers[0])}.')")
parts.append(f"""WITH target_module AS (SELECT m.id FROM public.modules m JOIN public.courses c ON c.id=m.course_id WHERE c.slug='statistics-data-science-python' AND m.order_index=11), seed(order_index,question_type,question,options,answer,difficulty,skill,explanation) AS (VALUES {','.join(values)})
INSERT INTO public.quiz_questions(module_id,order_index,question_type,question,options,answer,difficulty,skill,explanation,is_active,is_final_test)
SELECT target_module.id,s.order_index,s.question_type,s.question,s.options,s.answer,s.difficulty,s.skill,s.explanation,FALSE,TRUE FROM target_module CROSS JOIN seed s
ON CONFLICT(module_id,order_index) DO UPDATE SET question_type=EXCLUDED.question_type,question=EXCLUDED.question,options=EXCLUDED.options,answer=EXCLUDED.answer,difficulty=EXCLUDED.difficulty,skill=EXCLUDED.skill,explanation=EXCLUDED.explanation,is_active=FALSE,is_final_test=TRUE;
""")
parts.append("""
WITH c AS (SELECT id FROM public.courses WHERE slug='statistics-data-science-python')
INSERT INTO public.course_projects(course_id,slug,title,summary,brief_md,corpus_policy_md,starter_assets,minimum_version,advanced_version,functional_criteria,technical_criteria,rubric,reference_solution_md,is_published)
SELECT c.id,'prevision-ventes-segmentation-clients-python','Prévision des ventes et segmentation des clients avec Python','Construire une étude Data Science reproductible combinant prévision temporelle, segmentation client et recommandations métier.',
'# Brief\n\nVous êtes Data Scientist pour une entreprise de distribution. À partir des transactions clients et des ventes datées, vous devez contrôler la qualité des données, explorer les distributions, comparer des groupes, segmenter les clients et prévoir les ventes. La restitution doit expliquer les choix statistiques, quantifier l’incertitude et proposer des actions responsables.\n\n## Livrables\n- notebook professionnel réexécutable ;\n- rapport de qualité des données ;\n- analyse descriptive et tests statistiques ;\n- segmentation KMeans profilée ;\n- prévision de ventes avec validation temporelle ;\n- comparaison à des baselines ;\n- synthèse métier avec limites, éthique et recommandations.',
'# Politique des données\n\nUtiliser uniquement le corpus pédagogique fourni. Ne pas introduire de données personnelles externes. Documenter les transformations, exclusions et hypothèses. Toute recommandation doit rester proportionnée aux preuves.',
'[{"path":"/resources/statistics-data-science/transactions_clients.csv","purpose":"Transactions et comportement client"},{"path":"/resources/statistics-data-science/ventes_journalieres.csv","purpose":"Historique des ventes"},{"path":"/resources/statistics-data-science/dictionnaire_donnees.md","purpose":"Définition des variables"},{"path":"/resources/statistics-data-science/starter_notebook.ipynb","purpose":"Structure de départ"}]'::jsonb,
'["Nettoyer et documenter les données","Produire une analyse descriptive complète","Comparer au moins deux groupes avec taille d’effet","Créer 3 à 6 segments clients interprétables","Construire une baseline de prévision et un modèle évalué","Présenter cinq recommandations et leurs limites"]'::jsonb,
'["Comparer plusieurs méthodes de clustering","Tester la stabilité des segments","Construire une validation walk-forward multi-horizon","Ajouter des intervalles de prévision","Créer un pipeline reproductible et automatisé"]'::jsonb,
'["Les données sont contrôlées et traçables","Les tests répondent à des questions métier","Les segments sont stables et actionnables","La prévision est comparée à une baseline","Les recommandations reposent sur les résultats"]'::jsonb,
'["Notebook exécutable depuis un environnement propre","Transformations sans fuite de données","Random states fixés","Validation temporelle correcte","Métriques justifiées","Code factorisé et documenté","Limites et risques éthiques explicités"]'::jsonb,
'[{"criterion":"Qualité et préparation des données","points":8},{"criterion":"Analyse statistique","points":10},{"criterion":"Segmentation client","points":12},{"criterion":"Prévision des ventes","points":12},{"criterion":"Évaluation et robustesse","points":8},{"criterion":"Communication, éthique et recommandations","points":10}]'::jsonb,
'# Solution de référence\n\nLa solution attendue construit une table client au grain correct, standardise les variables dans un pipeline, compare plusieurs valeurs de K avec inertie, silhouette et stabilité, profile les segments sur les valeurs originales, crée des baselines naïve et saisonnière, évalue une prévision avec séparation temporelle et walk-forward, puis livre un notebook reproductible et une restitution métier honnête.',FALSE FROM c
ON CONFLICT(course_id,slug) DO UPDATE SET title=EXCLUDED.title,summary=EXCLUDED.summary,brief_md=EXCLUDED.brief_md,corpus_policy_md=EXCLUDED.corpus_policy_md,starter_assets=EXCLUDED.starter_assets,minimum_version=EXCLUDED.minimum_version,advanced_version=EXCLUDED.advanced_version,functional_criteria=EXCLUDED.functional_criteria,technical_criteria=EXCLUDED.technical_criteria,rubric=EXCLUDED.rubric,reference_solution_md=EXCLUDED.reference_solution_md,is_published=FALSE;

WITH p AS (SELECT cp.id project_id,cp.course_id FROM public.course_projects cp JOIN public.courses c ON c.id=cp.course_id WHERE c.slug='statistics-data-science-python' AND cp.slug='prevision-ventes-segmentation-clients-python'), seed(module_order,slug,title,description,deliverables,acceptance,ord) AS (VALUES
(0,'cadrer-et-auditer','Cadrer et auditer les données','Définir les questions, le grain, les variables et les risques de biais.','["Cadrage statistique","Rapport de qualité"]'::jsonb,'["Population et échantillon définis","Variables documentées","Anomalies tracées"]'::jsonb,0),
(2,'explorer-distributions','Explorer les distributions','Produire les résumés et visualisations utiles.','["Analyse descriptive","Graphiques commentés"]'::jsonb,'["Choix de mesures justifié","Outliers analysés","Messages explicites"]'::jsonb,1),
(6,'comparer-groupes','Comparer les groupes','Tester des différences et quantifier leur importance.','["Tests statistiques","Tailles d’effet","Intervalles"]'::jsonb,'["Hypothèses vérifiées","Test adapté","Conclusion métier prudente"]'::jsonb,2),
(8,'segmenter-clients','Segmenter les clients','Préparer, standardiser, entraîner KMeans et profiler les groupes.','["Pipeline de segmentation","Profils de segments"]'::jsonb,'["K justifié","Stabilité examinée","Segments actionnables"]'::jsonb,3),
(9,'prevoir-ventes','Prévoir les ventes','Construire baselines, modèle et validation temporelle.','["Prévisions","Comparatif de métriques","Graphiques temporels"]'::jsonb,'["Aucune fuite temporelle","Baseline battue ou limites expliquées","Horizon défini"]'::jsonb,4),
(10,'evaluer-robustesse','Évaluer la robustesse','Contrôler généralisation, erreurs et limites.','["Diagnostic train/validation","Analyse d’erreurs","Limites"]'::jsonb,'["Métriques justifiées","Sous-groupes contrôlés","Surapprentissage discuté"]'::jsonb,5),
(11,'restituer-et-recommander','Restituer et recommander','Livrer le notebook, le récit analytique et les actions métier.','["Notebook final","Synthèse exécutive","5 recommandations"]'::jsonb,'["Notebook reproductible","Faits et interprétations séparés","Éthique et suivi inclus"]'::jsonb,6))
INSERT INTO public.course_project_milestones(project_id,module_id,slug,title,description,deliverables,acceptance_criteria,order_index,is_published)
SELECT p.project_id,m.id,s.slug,s.title,s.description,s.deliverables,s.acceptance,s.ord,FALSE FROM p JOIN public.modules m ON m.course_id=p.course_id JOIN seed s ON s.module_order=m.order_index
ON CONFLICT(project_id,slug) DO UPDATE SET module_id=EXCLUDED.module_id,title=EXCLUDED.title,description=EXCLUDED.description,deliverables=EXCLUDED.deliverables,acceptance_criteria=EXCLUDED.acceptance_criteria,order_index=EXCLUDED.order_index,is_published=FALSE;

DO $$
DECLARE quiz_count INT; final_count INT; project_count INT; milestone_count INT; rubric_total INT; active_count INT; published_count INT;
BEGIN
 SELECT COUNT(*) FILTER (WHERE q.is_final_test=FALSE),COUNT(*) FILTER (WHERE q.is_final_test=TRUE),COUNT(*) FILTER (WHERE q.is_active) INTO quiz_count,final_count,active_count FROM public.quiz_questions q JOIN public.modules m ON m.id=q.module_id JOIN public.courses c ON c.id=m.course_id WHERE c.slug='statistics-data-science-python';
 SELECT COUNT(*),COUNT(*) FILTER (WHERE cp.is_published) INTO project_count,published_count FROM public.course_projects cp JOIN public.courses c ON c.id=cp.course_id WHERE c.slug='statistics-data-science-python';
 SELECT COUNT(*) INTO milestone_count FROM public.course_project_milestones pm JOIN public.course_projects cp ON cp.id=pm.project_id JOIN public.courses c ON c.id=cp.course_id WHERE c.slug='statistics-data-science-python';
 SELECT COALESCE(SUM((item->>'points')::INT),0) INTO rubric_total FROM public.course_projects cp JOIN public.courses c ON c.id=cp.course_id,LATERAL jsonb_array_elements(cp.rubric) item WHERE c.slug='statistics-data-science-python';
 IF quiz_count<>48 OR final_count<>12 OR project_count<>1 OR milestone_count<>7 OR rubric_total<>60 OR active_count<>0 OR published_count<>0 THEN RAISE EXCEPTION 'Chantier 4 Statistiques incomplet: quiz %, final %, projets %, jalons %, barème %, actifs %, publiés %',quiz_count,final_count,project_count,milestone_count,rubric_total,active_count,published_count; END IF;
END $$;
""")

out=Path('supabase/migrations/20260808_seed_statistics_data_science_quizzes_project.sql')
out.write_text('\n'.join(parts),encoding='utf-8')
print(out)
