from pathlib import Path

lessons = [
(0,0,'sql-postgresql-fondamentaux','Comprendre SQL et PostgreSQL','Situer SQL, PostgreSQL, une base, une table, une ligne et une colonne.',40,['Définir SQL et PostgreSQL','Identifier les objets principaux d’une base','Lire une table relationnelle'],['SQL est un langage déclaratif pour interroger et modifier les données.','PostgreSQL est un système de gestion de base de données relationnelle.','Une table représente une entité ou un événement avec des colonnes typées.'],"Observer les tables clients, produits et ventes, puis écrire SELECT * FROM clients LIMIT 5;",['Confondre SQL avec un tableur.','Modifier les données avant d’avoir compris le schéma.'],'Quelle différence existe entre SQL et PostgreSQL ?'),
(0,1,'premiere-requete-select','Écrire une première requête SELECT','Sélectionner des colonnes, utiliser des alias et limiter le résultat.',45,['Écrire SELECT et FROM','Créer des alias lisibles','Limiter les lignes retournées'],['SELECT choisit les colonnes à retourner.','FROM indique la table source.','LIMIT réduit le volume affiché pendant l’exploration.'],"Exécuter SELECT nom, segment AS categorie_client FROM clients ORDER BY nom LIMIT 10;",['Utiliser SELECT * dans les livrables finaux.','Donner des alias ambigus ou incohérents.'],'Pourquoi faut-il sélectionner explicitement les colonnes utiles ?'),
(1,0,'filtrer-avec-where','Filtrer avec WHERE','Construire des conditions fiables avec les opérateurs SQL.',50,['Utiliser les opérateurs de comparaison','Combiner AND, OR et NOT','Employer IN, BETWEEN et LIKE'],['WHERE filtre les lignes avant agrégation.','Les parenthèses rendent les conditions complexes explicites.','LIKE et ILIKE servent aux recherches textuelles.'],"Lister les clients actifs de Dakar dont le chiffre d’affaires dépasse 500000 FCFA.",['Mélanger AND et OR sans parenthèses.','Comparer une valeur NULL avec =.'],'Comment SQL évalue-t-il une condition combinant AND et OR ?'),
(1,1,'trier-dedoublonner-null','Trier, dédupliquer et gérer NULL','Utiliser ORDER BY, DISTINCT et les prédicats NULL.',45,['Trier sur plusieurs colonnes','Dédupliquer un résultat','Tester IS NULL et IS NOT NULL'],['ORDER BY peut combiner ordre croissant et décroissant.','DISTINCT agit sur l’ensemble des colonnes sélectionnées.','NULL représente une valeur absente ou inconnue.'],"Extraire les villes distinctes, les trier, puis repérer les clients sans téléphone.",['Remplacer NULL par une chaîne vide sans règle métier.','Utiliser DISTINCT pour masquer une mauvaise jointure.'],'Pourquoi DISTINCT ne doit-il pas servir à corriger une jointure incorrecte ?'),
(2,0,'expressions-case-coalesce','Créer des expressions avec CASE et COALESCE','Transformer les valeurs en colonnes métier exploitables.',50,['Créer une expression calculée','Catégoriser avec CASE','Gérer les valeurs absentes avec COALESCE'],['CASE traduit des règles métier en SQL.','COALESCE retourne la première valeur non nulle.','Les alias décrivent le sens du calcul produit.'],"Créer un statut de commande selon le montant et remplacer les régions absentes par Non renseignée.",['Coder des seuils sans les documenter.','Transformer toute valeur absente en zéro.'],'Dans quel cas COALESCE est-il préférable à CASE ?'),
(2,1,'fonctions-textes-dates-types','Transformer textes, dates et types','Utiliser les fonctions PostgreSQL pour nettoyer et enrichir.',55,['Nettoyer du texte','Extraire des composantes de date','Convertir les types avec CAST'],['TRIM, LOWER et UPPER normalisent le texte.','DATE_TRUNC et EXTRACT structurent l’analyse temporelle.','CAST rend les conversions explicites et contrôlables.'],"Normaliser les emails, calculer le mois de vente et convertir une colonne texte en date.",['Appliquer une conversion sans vérifier les formats.','Utiliser FORMAT pour un calcul qui exige un vrai type date.'],'Pourquoi conserver un vrai type date plutôt qu’un texte formaté ?'),
(3,0,'agregations-sql','Calculer des agrégats','Construire des indicateurs avec COUNT, SUM, AVG, MIN et MAX.',50,['Compter des lignes et valeurs uniques','Calculer sommes et moyennes','Comprendre le comportement avec NULL'],['COUNT(*) compte les lignes.','COUNT(colonne) ignore les valeurs NULL.','SUM et AVG nécessitent des types numériques cohérents.'],"Calculer le nombre de ventes, le chiffre d’affaires, la marge moyenne et le nombre de clients uniques.",['Confondre COUNT(*) et COUNT(colonne).','Moyenner des moyennes sans pondération.'],'Quelle différence existe entre COUNT(*) et COUNT(colonne) ?'),
(3,1,'group-by-having','Regrouper avec GROUP BY et HAVING','Produire des KPI par dimension et filtrer les groupes.',55,['Regrouper par une ou plusieurs dimensions','Filtrer après agrégation','Créer des agrégations conditionnelles'],['GROUP BY définit le grain du résultat.','HAVING filtre les groupes après calcul.','FILTER ou CASE permettent des agrégations conditionnelles.'],"Calculer le CA par région et ne conserver que les régions dépassant l’objectif.",['Sélectionner une colonne non agrégée absente du GROUP BY.','Utiliser WHERE pour filtrer un agrégat.'],'Pourquoi HAVING intervient-il après GROUP BY ?'),
(4,0,'inner-left-join','Maîtriser INNER JOIN et LEFT JOIN','Relier des tables avec les bonnes clés.',60,['Écrire une jointure explicite','Choisir INNER ou LEFT JOIN','Qualifier les colonnes'],['INNER JOIN conserve les correspondances.','LEFT JOIN conserve toutes les lignes de gauche.','La condition ON doit utiliser des clés compatibles.'],"Relier ventes, produits et clients pour afficher le détail enrichi des transactions.",['Joindre sur un libellé instable.','Oublier les alias de table dans une requête multi-tables.'],'Quand faut-il préférer LEFT JOIN à INNER JOIN ?'),
(4,1,'controler-jointures-cardinalite','Contrôler cardinalité et qualité des jointures','Détecter pertes, doublons et clés non uniques.',60,['Mesurer le nombre de lignes avant et après','Détecter les clés orphelines','Identifier une relation plusieurs-à-plusieurs'],['Une jointure peut multiplier les lignes si la clé de droite n’est pas unique.','Une anti-jointure détecte les références absentes.','Le grain doit rester stable après enrichissement.'],"Comparer COUNT(*) avant et après jointure, puis lister les codes produits sans correspondance.",['Ajouter DISTINCT après une multiplication de lignes.','Supposer qu’une clé est unique sans la vérifier.'],'Quel contrôle simple révèle une multiplication inattendue des lignes ?'),
(5,0,'sous-requetes-scalaires-in','Utiliser les sous-requêtes scalaires et IN','Comparer une valeur à un résultat intermédiaire.',50,['Écrire une sous-requête scalaire','Filtrer avec IN','Comparer à une moyenne globale'],['Une sous-requête scalaire doit retourner une seule valeur.','IN compare à un ensemble de valeurs.','Le résultat intermédiaire reste encapsulé dans la requête.'],"Identifier les ventes supérieures au montant moyen et les clients appartenant aux régions prioritaires.",['Retourner plusieurs lignes dans une sous-requête scalaire.','Utiliser IN avec un ensemble contenant des NULL sans contrôle.'],'Quelle contrainte s’applique à une sous-requête scalaire ?'),
(5,1,'exists-sous-requetes-correlees','Utiliser EXISTS et les sous-requêtes corrélées','Tester l’existence d’événements liés à chaque ligne.',55,['Comprendre une corrélation','Utiliser EXISTS et NOT EXISTS','Éviter les scans inutiles'],['EXISTS teste si au moins une ligne correspond.','La sous-requête corrélée référence la ligne courante.','NOT EXISTS est robuste pour détecter les absences.'],"Lister les clients ayant au moins une vente et ceux n’ayant jamais acheté.",['Sélectionner des colonnes inutiles dans EXISTS.','Confondre NOT IN et NOT EXISTS en présence de NULL.'],'Pourquoi NOT EXISTS est-il souvent plus sûr que NOT IN ?'),
(6,0,'cte-with','Structurer une requête avec WITH','Découper une analyse en étapes lisibles.',50,['Créer une CTE','Nommer les étapes métier','Réutiliser un résultat intermédiaire'],['WITH déclare des résultats intermédiaires nommés.','Chaque CTE doit avoir une responsabilité claire.','La requête finale assemble les étapes.'],"Créer des CTE ventes_mensuelles et objectifs, puis calculer le taux d’atteinte.",['Créer une CTE pour chaque ligne sans bénéfice.','Utiliser des noms techniques incompréhensibles.'],'Quel avantage principal apporte une CTE à une analyse complexe ?'),
(6,1,'cte-multiples-recursives','Enchaîner plusieurs CTE et découvrir la récursivité','Construire un pipeline SQL et comprendre WITH RECURSIVE.',55,['Chaîner plusieurs CTE','Contrôler chaque étape','Comprendre le cas d’usage récursif'],['Les CTE peuvent dépendre des précédentes.','WITH RECURSIVE traite des structures hiérarchiques ou séries.','Chaque étape doit être testable séparément.'],"Construire un pipeline ventes nettes, classement clients et synthèse finale ; générer ensuite une petite série de dates récursive.",['Créer une récursion sans condition d’arrêt.','Masquer une logique simple derrière trop de niveaux.'],'Quel élément empêche une CTE récursive de boucler indéfiniment ?'),
(7,0,'window-ranking','Classer avec les fonctions de fenêtre','Utiliser OVER, PARTITION BY, ROW_NUMBER, RANK et DENSE_RANK.',60,['Comprendre la fenêtre analytique','Classer dans chaque groupe','Choisir la bonne fonction de rang'],['Une fonction de fenêtre conserve le détail des lignes.','PARTITION BY redémarre le calcul par groupe.','RANK crée des trous après égalité, DENSE_RANK non.'],"Classer les produits par chiffre d’affaires dans chaque catégorie.",['Remplacer GROUP BY par une fenêtre sans comprendre le grain.','Oublier ORDER BY dans une fonction de classement.'],'Quelle différence existe entre RANK et DENSE_RANK ?'),
(7,1,'window-lag-cumul','Calculer cumuls et évolutions avec LAG','Comparer les périodes sans perdre le détail.',60,['Créer un cumul','Accéder à la ligne précédente','Calculer une variation temporelle'],['SUM(...) OVER calcule un cumul selon l’ordre.','LAG retourne la valeur précédente.','Le tri de la fenêtre définit la chronologie.'],"Calculer le CA mensuel, le cumul annuel et l’évolution par rapport au mois précédent.",['Oublier le partitionnement par année.','Calculer un pourcentage sans gérer la division par zéro.'],'Quel rôle joue ORDER BY dans un cumul de fenêtre ?'),
(8,0,'creer-vues','Créer des vues analytiques','Exposer une requête stable comme interface de données.',50,['Créer et remplacer une vue','Choisir les colonnes exposées','Documenter le contrat de la vue'],['CREATE VIEW encapsule une requête réutilisable.','Une vue ne stocke pas les résultats par défaut.','Les noms et types exposés forment un contrat.'],"Créer vue_ventes_enrichies avec les dimensions et mesures nécessaires au reporting.",['Exposer des colonnes sensibles.','Utiliser SELECT * dans une vue durable.'],'Pourquoi une vue doit-elle exposer explicitement ses colonnes ?'),
(8,1,'vues-materialisees','Utiliser les vues matérialisées','Choisir entre fraîcheur et performance.',55,['Créer une vue matérialisée','Actualiser les résultats','Comprendre les compromis'],['Une vue matérialisée stocke le résultat.','REFRESH MATERIALIZED VIEW met à jour les données.','Un index peut accélérer les consultations.'],"Créer une synthèse mensuelle matérialisée, l’indexer et mesurer son temps de lecture.",['Oublier la stratégie d’actualisation.','Utiliser une vue matérialisée pour des données devant être instantanées.'],'Quel compromis principal accompagne une vue matérialisée ?'),
(9,0,'insert-update-delete','Modifier les données avec INSERT, UPDATE et DELETE','Écrire des opérations ciblées et vérifiables.',55,['Insérer des lignes','Mettre à jour avec WHERE','Supprimer avec contrôle'],['INSERT ajoute des lignes conformes aux contraintes.','UPDATE et DELETE doivent être précédés d’un SELECT équivalent.','RETURNING montre les lignes modifiées.'],"Insérer un produit, corriger son prix avec UPDATE RETURNING, puis supprimer une ligne de test.",['Exécuter UPDATE ou DELETE sans WHERE.','Ignorer les contraintes et erreurs retournées.'],'Quelle vérification précède un UPDATE ou DELETE sensible ?'),
(9,1,'transactions-contraintes','Sécuriser avec transactions et contraintes','Garantir l’intégrité pendant les modifications.',55,['Utiliser BEGIN, COMMIT et ROLLBACK','Comprendre PK, FK, UNIQUE et CHECK','Tester une opération avant validation'],['Une transaction regroupe plusieurs opérations atomiques.','ROLLBACK annule les changements non validés.','Les contraintes protègent les règles structurelles.'],"Importer plusieurs lignes dans une transaction, provoquer une erreur contrôlée, puis annuler avec ROLLBACK.",['Valider avant les contrôles.','Désactiver les contraintes pour accélérer un import non maîtrisé.'],'Que garantit une transaction atomique ?'),
(10,0,'explain-index','Lire EXPLAIN et utiliser les index','Diagnostiquer une requête et choisir un index utile.',65,['Lire un plan simple','Identifier un scan séquentiel','Créer et évaluer un index'],['EXPLAIN montre la stratégie du planificateur.','EXPLAIN ANALYZE exécute la requête et mesure.','Un index aide surtout les filtres et jointures sélectifs.'],"Analyser une requête filtrant date et client, créer un index adapté, puis comparer les plans.",['Créer un index sur chaque colonne.','Utiliser EXPLAIN ANALYZE sur une modification sans transaction.'],'Pourquoi un index peut-il ralentir les écritures ?'),
(10,1,'roles-permissions','Gérer rôles et permissions','Appliquer le principe du moindre privilège.',50,['Créer un rôle','Accorder SELECT sur des vues','Révoquer les droits inutiles'],['GRANT accorde des permissions ciblées.','REVOKE retire des privilèges.','Les utilisateurs BI ne doivent pas modifier les tables sources.'],"Créer un rôle lecture_reporting et lui accorder uniquement SELECT sur les vues analytiques.",['Accorder tous les droits au rôle applicatif.','Partager un compte administrateur entre utilisateurs.'],'Que signifie le principe du moindre privilège ?'),
(11,0,'preparer-postgresql-power-bi','Préparer PostgreSQL pour Power BI','Construire une couche analytique stable et documentée.',60,['Préparer des vues BI','Limiter les colonnes et lignes','Documenter les types et clés'],['Power BI doit consommer des vues orientées analyse.','Les types PostgreSQL doivent être compatibles et explicites.','La requête source doit rester contrôlable et performante.'],"Créer une vue ventes_power_bi avec dates, dimensions, CA et marge, puis vérifier son grain.",['Connecter Power BI directement à toutes les tables brutes.','Exposer des identifiants ou données personnelles inutiles.'],'Pourquoi préparer des vues dédiées avant la connexion Power BI ?'),
(11,1,'connecter-actualiser-documenter','Connecter, actualiser et remettre l’analyse','Finaliser la chaîne PostgreSQL vers Power BI.',65,['Configurer la connexion','Choisir Import ou DirectQuery','Documenter actualisation et contrôles'],['Le mode Import optimise souvent l’expérience analytique.','DirectQuery interroge la source à chaque interaction.','La documentation couvre source, vues, droits et actualisation.'],"Connecter Power BI à la vue analytique, contrôler les totaux, définir l’actualisation et rédiger trois recommandations métier.",['Publier sans tester les droits du rôle lecture.','Oublier de comparer les totaux SQL et Power BI.'],'Quels contrôles doivent précéder la remise du projet final ?'),
]

def esc(s): return s.replace("'", "''")
rows=[]
for mo,lo,slug,title,summary,minutes,objectives,concepts,demo,errors,prompt in lessons:
    content=f"# {title}\n\n## Objectif\n\n{summary}\n\n## Concepts essentiels\n\n" + "\n".join(f"- {x}" for x in concepts) + f"\n\n## Exemple PostgreSQL\n\n{demo}\n\n## Erreurs à éviter\n\n" + "\n".join(f"- {x}" for x in errors) + "\n\n## Résumé opérationnel\n\nÉcrivez la requête, vérifiez le nombre de lignes, contrôlez un échantillon et documentez le grain du résultat."
    obj="["+", ".join('"'+x.replace('"','\\"')+'"' for x in objectives)+"]"
    rows.append(f"    ({mo},{lo},'{slug}','{esc(title)}','{esc(summary)}','lesson',{minutes},'{obj}'::jsonb,$lesson${content}$lesson$,'{esc(prompt)}')")

sql="""-- KORYXA FORMATION — SQL DATA ANALYST AVEC POSTGRESQL — CHANTIER 2
-- Contenu pédagogique complet : 24 leçons, toutes non publiées.

WITH lesson_seed(module_order,lesson_order,slug,title,summary,lesson_type,minutes,objectives,content_md,validation_prompt) AS (
    VALUES
""" + ",\n".join(rows) + """
), target AS (
    SELECT m.id AS module_id, m.order_index
    FROM public.modules m
    JOIN public.courses c ON c.id = m.course_id
    WHERE c.slug = 'sql-data-analyst'
)
INSERT INTO public.lessons(
    module_id,slug,title,summary,order_index,lesson_type,estimated_minutes,
    objectives,content_md,source_refs,validation_prompt,is_published
)
SELECT t.module_id,l.slug,l.title,l.summary,l.lesson_order,l.lesson_type,l.minutes,
       l.objectives,l.content_md,'["KORYXA SQL Data Analyst", "PostgreSQL"]'::jsonb,l.validation_prompt,FALSE
FROM lesson_seed l
JOIN target t ON t.order_index = l.module_order
ON CONFLICT (module_id,slug) DO UPDATE SET
    title = EXCLUDED.title,
    summary = EXCLUDED.summary,
    order_index = EXCLUDED.order_index,
    lesson_type = EXCLUDED.lesson_type,
    estimated_minutes = EXCLUDED.estimated_minutes,
    objectives = EXCLUDED.objectives,
    content_md = EXCLUDED.content_md,
    source_refs = EXCLUDED.source_refs,
    validation_prompt = EXCLUDED.validation_prompt,
    is_published = FALSE;

DO $$
DECLARE lesson_count INT; module_coverage INT; published_count INT;
BEGIN
    SELECT COUNT(*), COUNT(DISTINCT m.id), COUNT(*) FILTER (WHERE l.is_published)
    INTO lesson_count, module_coverage, published_count
    FROM public.lessons l
    JOIN public.modules m ON m.id=l.module_id
    JOIN public.courses c ON c.id=m.course_id
    WHERE c.slug='sql-data-analyst';
    IF lesson_count<>24 OR module_coverage<>12 OR published_count<>0 THEN
        RAISE EXCEPTION 'Contenu SQL incomplet: leçons %, modules couverts %, publiées %', lesson_count, module_coverage, published_count;
    END IF;
END $$;
"""
Path('supabase/migrations/20260731_seed_sql_data_analyst_lesson_content.sql').write_text(sql,encoding='utf-8')
print('generated', len(lessons), 'lessons')
