-- KORYXA FORMATION — SQL DATA ANALYST AVEC POSTGRESQL — CHANTIER 3
-- Datasets, scripts, exercices guidés et ressources officielles. Tout reste non publié.

WITH course_row AS (
    SELECT id FROM public.courses WHERE slug='sql-data-analyst'
), module_rows AS (
    SELECT m.id,m.order_index FROM public.modules m JOIN course_row c ON c.id=m.course_id
), exercise_seed(module_order,slug,title,exercise_type,brief_md,starter_files,expected_result_md,hints,solution_md,estimated_minutes) AS (
    VALUES
    (0,'explorer-base-postgresql','Explorer une base PostgreSQL','guided','Installez le schéma pédagogique, inspectez les cinq tables et exécutez vos premières requêtes SELECT.','[{"name": "01_schema_postgresql.sql", "path": "/resources/sql-data-analyst/01_schema_postgresql.sql", "purpose": "Schéma relationnel pédagogique"}, {"name": "02_chargement_donnees.sql", "path": "/resources/sql-data-analyst/02_chargement_donnees.sql", "purpose": "Chargement des CSV avec psql"}, {"name": "03_requetes_depart.sql", "path": "/resources/sql-data-analyst/03_requetes_depart.sql", "purpose": "Requêtes d’exploration et vue enrichie"}, {"name": "04_solutions_reference.sql", "path": "/resources/sql-data-analyst/04_solutions_reference.sql", "purpose": "Corrigés de référence séparés"}]'::jsonb,'Un schéma formation_sql créé, cinq tables visibles et une requête retournant dix clients.','["Commencez par 01_schema_postgresql.sql.", "Utilisez information_schema.tables pour inspecter le schéma."]'::jsonb,'Exécuter le schéma, charger les données, définir search_path puis interroger clients avec SELECT et LIMIT.',45),
    (1,'filtrer-trier-clients','Filtrer et trier les clients','guided','Produisez une liste des clients PME ou Grand compte, situés dans deux régions choisies, triée par segment puis nom.','[{"name": "03_requetes_depart.sql", "path": "/resources/sql-data-analyst/03_requetes_depart.sql", "purpose": "Requêtes d’exploration et vue enrichie"}, {"name": "04_solutions_reference.sql", "path": "/resources/sql-data-analyst/04_solutions_reference.sql", "purpose": "Corrigés de référence séparés"}]'::jsonb,'Une extraction sans doublon avec colonnes explicites, filtres corrects et tri stable.','["Utilisez IN pour plusieurs valeurs.", "Ajoutez des parenthèses lorsque AND et OR se combinent."]'::jsonb,'Sélectionner code_client, client, segment et code_region, filtrer avec IN puis trier avec ORDER BY segment, client.',45),
    (2,'calculer-statut-marge','Créer des colonnes métier','guided','À partir des ventes et produits, calculez chiffre d’affaires, marge et une catégorie de rentabilité avec CASE.','[{"name": "03_requetes_depart.sql", "path": "/resources/sql-data-analyst/03_requetes_depart.sql", "purpose": "Requêtes d’exploration et vue enrichie"}, {"name": "04_solutions_reference.sql", "path": "/resources/sql-data-analyst/04_solutions_reference.sql", "purpose": "Corrigés de référence séparés"}]'::jsonb,'Une requête détaillée avec CA, marge et statut Fort, Moyen ou Faible.','["Joignez ventes et produits sur code_produit.", "Calculez d’abord la marge avant CASE."]'::jsonb,'Créer une CTE ou une sous-requête calculant montant et marge, puis appliquer CASE sur la marge.',55),
    (3,'kpi-par-region','Calculer les KPI par région','challenge','Calculez chiffre d’affaires, marge, quantité, nombre de ventes et clients actifs par région, puis filtrez les régions au-dessus d’un seuil.','[{"name": "03_requetes_depart.sql", "path": "/resources/sql-data-analyst/03_requetes_depart.sql", "purpose": "Requêtes d’exploration et vue enrichie"}, {"name": "04_solutions_reference.sql", "path": "/resources/sql-data-analyst/04_solutions_reference.sql", "purpose": "Corrigés de référence séparés"}]'::jsonb,'Une ligne par région avec cinq KPI fiables, triée par chiffre d’affaires décroissant.','["Le grain final est la région.", "Utilisez COUNT(DISTINCT code_client)."]'::jsonb,'Joindre les tables ou utiliser ventes_enrichies, GROUP BY region, calculer les agrégats et filtrer avec HAVING.',60),
    (4,'controler-jointures','Relier les tables sans fausser les résultats','debug','Construisez la vue ventes enrichies et démontrez qu’aucune vente n’est perdue ou multipliée lors des jointures.','[{"name": "01_schema_postgresql.sql", "path": "/resources/sql-data-analyst/01_schema_postgresql.sql", "purpose": "Schéma relationnel pédagogique"}, {"name": "02_chargement_donnees.sql", "path": "/resources/sql-data-analyst/02_chargement_donnees.sql", "purpose": "Chargement des CSV avec psql"}, {"name": "03_requetes_depart.sql", "path": "/resources/sql-data-analyst/03_requetes_depart.sql", "purpose": "Requêtes d’exploration et vue enrichie"}, {"name": "04_solutions_reference.sql", "path": "/resources/sql-data-analyst/04_solutions_reference.sql", "purpose": "Corrigés de référence séparés"}]'::jsonb,'Une vue enrichie de 120 lignes et un rapport de contrôle des clés orphelines.','["Comparez COUNT(*) avant et après jointure.", "Utilisez LEFT JOIN puis WHERE clé_droite IS NULL pour les orphelins."]'::jsonb,'Créer la vue avec les clés primaires/étrangères, comparer les comptes et exécuter des anti-jointures pour chaque référentiel.',65),
    (5,'clients-au-dessus-moyenne','Analyser avec des sous-requêtes','challenge','Identifiez les clients dont le chiffre d’affaires dépasse la moyenne des clients et ceux n’ayant jamais acheté.','[{"name": "03_requetes_depart.sql", "path": "/resources/sql-data-analyst/03_requetes_depart.sql", "purpose": "Requêtes d’exploration et vue enrichie"}, {"name": "04_solutions_reference.sql", "path": "/resources/sql-data-analyst/04_solutions_reference.sql", "purpose": "Corrigés de référence séparés"}]'::jsonb,'Deux résultats : clients au-dessus de la moyenne et clients sans vente.','["Agrégerez d’abord par client.", "NOT EXISTS est robuste pour détecter les absences."]'::jsonb,'Créer une sous-requête agrégeant le CA client, comparer chaque CA à AVG, puis utiliser NOT EXISTS pour les clients sans vente.',60),
    (6,'pipeline-cte-objectifs','Construire un pipeline avec des CTE','challenge','Comparez le chiffre d’affaires mensuel aux objectifs avec plusieurs CTE nommées.','[{"name": "03_requetes_depart.sql", "path": "/resources/sql-data-analyst/03_requetes_depart.sql", "purpose": "Requêtes d’exploration et vue enrichie"}, {"name": "04_solutions_reference.sql", "path": "/resources/sql-data-analyst/04_solutions_reference.sql", "purpose": "Corrigés de référence séparés"}]'::jsonb,'Un tableau mois, CA, objectif, écart et taux d’atteinte.','["Une CTE pour le CA mensuel, une pour les objectifs.", "Utilisez NULLIF pour la division."]'::jsonb,'Créer ca_mensuel et objectifs_mensuels, les joindre sur le mois puis calculer écart et taux avec NULLIF.',65),
    (7,'classement-cumul-evolution','Créer classements et cumuls','challenge','Classez les produits dans chaque catégorie et calculez le cumul mensuel ainsi que l’évolution par rapport au mois précédent.','[{"name": "03_requetes_depart.sql", "path": "/resources/sql-data-analyst/03_requetes_depart.sql", "purpose": "Requêtes d’exploration et vue enrichie"}, {"name": "04_solutions_reference.sql", "path": "/resources/sql-data-analyst/04_solutions_reference.sql", "purpose": "Corrigés de référence séparés"}]'::jsonb,'Un classement par catégorie et une série mensuelle avec cumul et variation.','["Utilisez DENSE_RANK avec PARTITION BY categorie.", "Utilisez LAG sur les agrégats mensuels."]'::jsonb,'Agrégérer les ventes, appliquer DENSE_RANK, puis créer une CTE mensuelle avec SUM OVER et LAG.',75),
    (8,'vues-reporting','Créer des vues analytiques','guided','Créez une vue détaillée et une vue matérialisée mensuelle prêtes pour le reporting.','[{"name": "01_schema_postgresql.sql", "path": "/resources/sql-data-analyst/01_schema_postgresql.sql", "purpose": "Schéma relationnel pédagogique"}, {"name": "02_chargement_donnees.sql", "path": "/resources/sql-data-analyst/02_chargement_donnees.sql", "purpose": "Chargement des CSV avec psql"}, {"name": "03_requetes_depart.sql", "path": "/resources/sql-data-analyst/03_requetes_depart.sql", "purpose": "Requêtes d’exploration et vue enrichie"}, {"name": "04_solutions_reference.sql", "path": "/resources/sql-data-analyst/04_solutions_reference.sql", "purpose": "Corrigés de référence séparés"}]'::jsonb,'Une vue ventes_enrichies et une synthese_mensuelle matérialisée avec index utile.','["Évitez SELECT * dans une vue durable.", "Documentez la stratégie de REFRESH."]'::jsonb,'Créer les deux objets, ajouter un index sur mois/région et tester REFRESH MATERIALIZED VIEW.',65),
    (9,'transaction-import-correction','Modifier les données en sécurité','debug','Dans une transaction, insérez un produit de test, modifiez son prix, contrôlez RETURNING puis annulez les changements.','[{"name": "03_requetes_depart.sql", "path": "/resources/sql-data-analyst/03_requetes_depart.sql", "purpose": "Requêtes d’exploration et vue enrichie"}, {"name": "04_solutions_reference.sql", "path": "/resources/sql-data-analyst/04_solutions_reference.sql", "purpose": "Corrigés de référence séparés"}]'::jsonb,'Une séquence BEGIN/INSERT/UPDATE/DELETE/ROLLBACK sans impact persistant.','["Exécutez SELECT avant UPDATE ou DELETE.", "Utilisez RETURNING pour vérifier."]'::jsonb,'BEGIN, INSERT, UPDATE ... RETURNING, DELETE ... RETURNING, contrôles SELECT, puis ROLLBACK.',55),
    (10,'explain-index-role','Optimiser et sécuriser','challenge','Analysez une requête avec EXPLAIN ANALYZE, créez un index pertinent et un rôle lecture_reporting limité aux vues.','[{"name": "03_requetes_depart.sql", "path": "/resources/sql-data-analyst/03_requetes_depart.sql", "purpose": "Requêtes d’exploration et vue enrichie"}, {"name": "04_solutions_reference.sql", "path": "/resources/sql-data-analyst/04_solutions_reference.sql", "purpose": "Corrigés de référence séparés"}]'::jsonb,'Un plan comparatif avant/après et un rôle ne disposant que de SELECT sur les vues.','["Indexez les colonnes réellement filtrées ou jointes.", "GRANT USAGE sur le schéma peut être nécessaire."]'::jsonb,'Mesurer le plan, créer un index composite adapté, remesurer, créer le rôle et accorder USAGE puis SELECT uniquement.',75),
    (11,'postgresql-vers-power-bi','Préparer PostgreSQL pour Power BI','challenge','Préparez une vue finale pour Power BI, vérifiez le grain, les totaux, les types, les droits et la procédure d’actualisation.','[{"name": "01_schema_postgresql.sql", "path": "/resources/sql-data-analyst/01_schema_postgresql.sql", "purpose": "Schéma relationnel pédagogique"}, {"name": "02_chargement_donnees.sql", "path": "/resources/sql-data-analyst/02_chargement_donnees.sql", "purpose": "Chargement des CSV avec psql"}, {"name": "03_requetes_depart.sql", "path": "/resources/sql-data-analyst/03_requetes_depart.sql", "purpose": "Requêtes d’exploration et vue enrichie"}, {"name": "04_solutions_reference.sql", "path": "/resources/sql-data-analyst/04_solutions_reference.sql", "purpose": "Corrigés de référence séparés"}]'::jsonb,'Une vue ventes_power_bi documentée, contrôlée et accessible au rôle de lecture.','["Exposez seulement les colonnes utiles.", "Comparez les totaux SQL avec ceux du rapport."]'::jsonb,'Créer la vue finale, accorder SELECT au rôle, contrôler COUNT/SUM, connecter Power BI et documenter Import ou DirectQuery.',80)
)
INSERT INTO public.exercises(course_id,module_id,slug,title,exercise_type,brief_md,starter_files,expected_result_md,hints,solution_md,order_index,estimated_minutes,is_published)
SELECT c.id,m.id,e.slug,e.title,e.exercise_type,e.brief_md,e.starter_files,e.expected_result_md,e.hints,e.solution_md,0,e.estimated_minutes,FALSE
FROM course_row c JOIN module_rows m ON TRUE JOIN exercise_seed e ON e.module_order=m.order_index
ON CONFLICT(course_id,slug) DO UPDATE SET
 module_id=EXCLUDED.module_id,title=EXCLUDED.title,exercise_type=EXCLUDED.exercise_type,brief_md=EXCLUDED.brief_md,
 starter_files=EXCLUDED.starter_files,expected_result_md=EXCLUDED.expected_result_md,hints=EXCLUDED.hints,
 solution_md=EXCLUDED.solution_md,estimated_minutes=EXCLUDED.estimated_minutes,is_published=FALSE;

WITH c AS (SELECT id FROM public.courses WHERE slug='sql-data-analyst'),
resources(module_order,slug,title,summary,content_md,ord) AS (
    VALUES
    (0,'postgresql-tutorial-start','Tutoriel PostgreSQL','Tutoriel officiel pour débuter avec PostgreSQL.','# Ressource officielle PostgreSQL\n\n[Tutoriel PostgreSQL](https://www.postgresql.org/docs/current/tutorial-start.html)',0),
    (1,'postgresql-select','SELECT','Documentation officielle de la commande SELECT.','# Ressource officielle PostgreSQL\n\n[SELECT](https://www.postgresql.org/docs/current/sql-select.html)',1),
    (2,'postgresql-functions','Fonctions et opérateurs','Référence officielle des fonctions et opérateurs PostgreSQL.','# Ressource officielle PostgreSQL\n\n[Fonctions et opérateurs](https://www.postgresql.org/docs/current/functions.html)',2),
    (3,'postgresql-aggregate','Fonctions d’agrégation','Référence officielle COUNT, SUM, AVG, MIN et MAX.','# Ressource officielle PostgreSQL\n\n[Fonctions d’agrégation](https://www.postgresql.org/docs/current/functions-aggregate.html)',3),
    (4,'postgresql-queries-table-expressions','Jointures et expressions de table','Documentation officielle sur FROM, JOIN, WHERE, GROUP BY et HAVING.','# Ressource officielle PostgreSQL\n\n[Jointures et expressions de table](https://www.postgresql.org/docs/current/queries-table-expressions.html)',4),
    (5,'postgresql-subqueries','Sous-requêtes','Documentation officielle sur les expressions de sous-requêtes.','# Ressource officielle PostgreSQL\n\n[Sous-requêtes](https://www.postgresql.org/docs/current/functions-subquery.html)',5),
    (6,'postgresql-with','CTE avec WITH','Documentation officielle sur les requêtes WITH et récursives.','# Ressource officielle PostgreSQL\n\n[CTE avec WITH](https://www.postgresql.org/docs/current/queries-with.html)',6),
    (7,'postgresql-window','Fonctions de fenêtre','Tutoriel officiel sur les fonctions de fenêtre.','# Ressource officielle PostgreSQL\n\n[Fonctions de fenêtre](https://www.postgresql.org/docs/current/tutorial-window.html)',7),
    (8,'postgresql-create-view','CREATE VIEW','Référence officielle pour créer des vues.','# Ressource officielle PostgreSQL\n\n[CREATE VIEW](https://www.postgresql.org/docs/current/sql-createview.html)',8),
    (9,'postgresql-transactions','Transactions','Tutoriel officiel sur BEGIN, COMMIT et ROLLBACK.','# Ressource officielle PostgreSQL\n\n[Transactions](https://www.postgresql.org/docs/current/tutorial-transactions.html)',9),
    (10,'postgresql-explain','EXPLAIN et performance','Documentation officielle sur l’utilisation d’EXPLAIN.','# Ressource officielle PostgreSQL\n\n[EXPLAIN et performance](https://www.postgresql.org/docs/current/using-explain.html)',10),
    (11,'postgresql-privileges','Privilèges et rôles','Documentation officielle sur les privilèges PostgreSQL.','# Ressource officielle PostgreSQL\n\n[Privilèges et rôles](https://www.postgresql.org/docs/current/ddl-priv.html)',11)
)
INSERT INTO public.theory_resources(course_id,module_id,slug,title,summary,content_md,resource_type,order_index,is_published)
SELECT c.id,m.id,r.slug,r.title,r.summary,r.content_md,'reference',r.ord,FALSE
FROM c JOIN resources r ON TRUE JOIN public.modules m ON m.course_id=c.id AND m.order_index=r.module_order
ON CONFLICT(course_id,slug) DO UPDATE SET
 module_id=EXCLUDED.module_id,title=EXCLUDED.title,summary=EXCLUDED.summary,content_md=EXCLUDED.content_md,
 resource_type=EXCLUDED.resource_type,order_index=EXCLUDED.order_index,is_published=FALSE;

DO $$
DECLARE exercise_count INT; resource_count INT; module_exercises INT; published_count INT;
BEGIN
 SELECT COUNT(*),COUNT(DISTINCT e.module_id),COUNT(*) FILTER (WHERE e.is_published)
 INTO exercise_count,module_exercises,published_count
 FROM public.exercises e JOIN public.courses c ON c.id=e.course_id WHERE c.slug='sql-data-analyst';
 SELECT COUNT(*) INTO resource_count FROM public.theory_resources r JOIN public.courses c ON c.id=r.course_id WHERE c.slug='sql-data-analyst';
 IF exercise_count<>12 OR module_exercises<>12 OR resource_count<>12 OR published_count<>0 THEN
  RAISE EXCEPTION 'Chantier 3 SQL incomplet: exercices %, modules %, ressources %, publiés %',exercise_count,module_exercises,resource_count,published_count;
 END IF;
END $$;
